In [1]:
import cv2
import pandas as pd
import numpy as np
# 2cm x 2cm


In [2]:
not_detect_imgs = []
corners_dict = {}
for idx in range(1,26): # testing first two imgs
    img = cv2.imread(f"img{idx}.jpg")
    img = np.uint8(img)
    gray_scaled_img = cv2.cvtColor(img, cv2.COLOR_HSV2BGR)

    ans, corners= cv2.findChessboardCorners(gray_scaled_img, patternSize= (9,6))
    if ans is False:
        not_detect_imgs.append(idx)
    else:
        corners_dict[idx] = corners
    #print(len(corners))
    
    
    #print(corners)
    # x = corners[0][0]
    # y = corners[0][1]
    # print(f"x: {x}, y: {y}")
    # print("ans", ans)
    # print('corner:', corners)
    # print('------------')

# print(not_detect_imgs)
# print(corners_dict)

print(not_detect_imgs)

[4, 5, 10, 12, 13, 19]


In [3]:

for corners in corners_dict.values():
    for coords in corners: #2621. 2016.5
        #print(i[0])
        x = coords[0][0]
        y = coords[0][1]
        print(x,y)
        center = (int(x), int(y))
        print(center)
        break

618.9795 319.6103
(618, 319)
544.98474 316.937
(544, 316)
610.429 336.40582
(610, 336)
581.5 405.5
(581, 405)
602.76904 356.7643
(602, 356)
627.68677 378.15363
(627, 378)
608.0 427.0
(608, 427)
601.5 171.5
(601, 171)
551.5229 238.32903
(551, 238)
558.09174 157.32755
(558, 157)
704.82367 227.25104
(704, 227)
703.4904 299.05634
(703, 299)
610.579 289.07443
(610, 289)
532.23724 335.06366
(532, 335)
551.0438 374.34348
(551, 374)
555.0885 355.52173
(555, 355)
519.81104 392.5449
(519, 392)
637.2707 403.75052
(637, 403)
642.0843 278.60364
(642, 278)


In [4]:
for i in corners_dict.values(): # checking amount of corners in img2
    print(len(i))

54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54


In [ ]:

all_result = {}

def click_event(event, x, y, flags, param):
    current_img = param['img']
    current_name = param['name']
    if event == cv2.EVENT_LBUTTONDBLCLK and len(param['point'])<= 4:
        print(x,y) # coordinate
        font = cv2.FONT_HERSHEY_SIMPLEX
        cv2.putText(current_img, f'{x}, {y}', (x,y), font, 1, (255,0,0), 2)
        cv2.imshow(window_name, current_img)
        param['point'].append([x,y])
    
    if event == cv2.EVENT_RBUTTONDBLCLK and len(param['point'])<= 4:
        print(x,y)
        font = cv2.FONT_HERSHEY_SIMPLEX
        b,g,r = current_img[y,x] 
        cv2.putText(img,f'{b}, {g}, {r}', (x,y), font, 1, (255, 255,0), 2)
        cv2.imshow(window_name, current_img)
        #points += [x,y]
    


        
            

    print(f"Manual Points: {param['point']}")

window_name = 'chessboard_tool'

# read input image
for idx in range(1,26):

    img = cv2.imread(f'img{idx}.jpg')

# convert the input image to a grayscale
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

    # Find the chess board corners
    ret, corners = cv2.findChessboardCorners(gray, (9,6),None)
    print(corners)
    # if chessboard corners are detected
    if ret == True:
    
        # Draw and display the corners
        img = cv2.drawChessboardCorners(img, (9,6), corners,ret)
        cv2.imshow('Chessboard',img)
        cv2.waitKey(0)

    elif ret == False:
        cv2.imshow(window_name, img)
        # clicking (TL -> TR -> BR -> BL)
        manual_pts = []
        cv2.setMouseCallback(window_name, click_event, param= {'img': img, 'name': f'Image{idx},', 'point':manual_pts})
        cv2.waitKey(0)
        manual_pts = np.array(manual_pts)
        cv2.destroyAllWindows()
        



[[[619.1612  319.1798 ]]

 [[619.12994 354.84903]]

 [[619.0211  390.90298]]

 [[618.7946  426.566  ]]

 [[619.3388  463.98865]]

 [[618.8307  501.92792]]

 [[619.121   540.15546]]

 [[618.54236 578.6859 ]]

 [[619.7425  618.4025 ]]

 [[583.3251  318.7181 ]]

 [[583.18225 353.68164]]

 [[582.73846 390.14258]]

 [[582.93506 426.35675]]

 [[582.1687  463.8268 ]]

 [[582.2361  501.20258]]

 [[581.2969  540.43353]]

 [[581.3998  578.80646]]

 [[580.907   619.0484 ]]

 [[546.6431  317.12076]]

 [[545.92944 352.93387]]

 [[545.5869  389.02826]]

 [[544.99866 426.2418 ]]

 [[544.50494 463.43008]]

 [[543.61255 501.54608]]

 [[543.3274  540.1849 ]]

 [[542.3612  579.2098 ]]

 [[543.4806  619.10114]]

 [[509.5606  316.4879 ]]

 [[509.05997 351.9201 ]]

 [[507.96918 388.78214]]

 [[507.53644 425.38687]]

 [[506.19733 463.17084]]

 [[505.51132 501.31464]]

 [[504.8001  540.6175 ]]

 [[504.4324  579.2838 ]]

 [[501.42184 619.5486 ]]

 [[472.35645 315.01434]]

 [[471.09363 350.9698 ]]

 [[470.53583

In [ ]:
print(manual_pts)

points []


In [ ]:

#gray_scaled_img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)

def click_event(event, x, y, flags, param):
    current_img = param['img']
    current_name = param['name']
    if event == cv2.EVENT_LBUTTONDBLCLK:
        print(x,y) # coordinate
        font = cv2.FONT_HERSHEY_SIMPLEX
        cv2.putText(current_img, f'{x}, {y}', (x,y), font, 1, (255,0,0), 2)
        cv2.imshow(window_name, current_img)
    
    if event == cv2.EVENT_RBUTTONDBLCLK:
        print(x,y)
        font = cv2.FONT_HERSHEY_SIMPLEX
        b,g,r = current_img[y,x] 
        cv2.putText(img,f'{b}, {g}, {r}', (x,y), font, 1, (255, 255,0), 2)
        cv2.imshow(window_name, current_img)

def resize(img, scale_percentage):
    width = int(img.shape[1]* scale_percentage/100)
    height = int(img.shape[0] * scale_percentage/100)
    dim = (width, height)

    resized_img = cv2.resize(img, dim, interpolation= cv2.INTER_AREA)
    return resized_img

window_name = 'chessboard_tool'
img1 = cv2.imread('img1.jpg')
img1 = cv2.drawChessboardCorners(img, (7,6), corners,ret)

#img1 = resize(img1, scale_percentage= 20)
cv2.imshow(window_name, img1)
cv2.setMouseCallback(window_name, click_event, param= {'img': img1, 'name': 'Image1'})
cv2.waitKey(0)
cv2.destroyAllWindows()



In [ ]:
# window_name = 'chessboard_tool'
# img2 = cv2.imread('img2.jpg',1)

# img2 = resize(img2, scale_percentage= 40)
# cv2.imshow(window_name, img2)
# cv2.setMouseCallback(window_name, click_event,param= {'img': img2, 'name': 'Image2'})
# cv2.waitKey(0)

# cv2.destroyAllWindows()