In [116]:
import cv2
import pandas as pd
import numpy as np
# 2cm x 2cm


In [117]:
not_detect_imgs = []
corners_dict = {}
for idx in range(1,26): # testing first two imgs
    img = cv2.imread(f"img{idx}.jpg")
    img = np.uint8(img)
    gray_scaled_img = cv2.cvtColor(img, cv2.COLOR_HSV2BGR)

    ans, corners= cv2.findChessboardCorners(gray_scaled_img, patternSize= (9,6))
    if ans is False:
        not_detect_imgs.append(idx)
    else:
        corners_dict[idx] = corners
    #print(len(corners))
    
    
    #print(corners)
    # x = corners[0][0]
    # y = corners[0][1]
    # print(f"x: {x}, y: {y}")
    # print("ans", ans)
    # print('corner:', corners)
    # print('------------')

# print(not_detect_imgs)
# print(corners_dict)

print(not_detect_imgs)

[4, 5, 6, 10, 12, 13, 19]


In [118]:

for corners in corners_dict.values():
    for coords in corners: #2621. 2016.5
        #print(i[0])
        x = coords[0][0]
        y = coords[0][1]
        print(x,y)
        center = (int(x), int(y))
        print(center)
        break

618.98334 319.60272
(618, 319)
544.97595 316.93356
(544, 316)
610.4357 336.41296
(610, 336)
602.717 356.7525
(602, 356)
627.7335 378.20477
(627, 378)
608.5 427.0
(608, 427)
601.5 171.5
(601, 171)
551.50494 238.26869
(551, 238)
558.17255 157.28372
(558, 157)
704.89825 227.15437
(704, 227)
703.5418 299.07608
(703, 299)
610.5784 289.06122
(610, 289)
532.2227 335.0679
(532, 335)
551.0498 374.34402
(551, 374)
555.0785 355.52313
(555, 355)
519.7551 392.36423
(519, 392)
637.2728 403.72522
(637, 403)
641.91614 278.5898
(641, 278)


In [119]:
for i in corners_dict.values(): # checking amount of corners in img2
    print(len(i))

54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54


In [ ]:

points = []
def click_event(event, x, y, flags, param, points = []):
    current_img = param['img']
    current_name = param['name']
    if event == cv2.EVENT_LBUTTONDBLCLK:
        print(x,y) # coordinate
        font = cv2.FONT_HERSHEY_SIMPLEX
        cv2.putText(current_img, f'{x}, {y}', (x,y), font, 1, (255,0,0), 2)
        cv2.imshow(window_name, current_img)
        points += [[x,y]]
    
    if event == cv2.EVENT_RBUTTONDBLCLK:
        print(x,y)
        font = cv2.FONT_HERSHEY_SIMPLEX
        b,g,r = current_img[y,x] 
        cv2.putText(img,f'{b}, {g}, {r}', (x,y), font, 1, (255, 255,0), 2)
        cv2.imshow(window_name, current_img)
        points += [x,y]
        coord_undetec = points
            

    print(f' Manual Points: {points}')
    return coord_undetec

    return points

window_name = 'chessboard_tool'

# read input image
for idx in range(1,26):

    img = cv2.imread(f'img{idx}.jpg')

# convert the input image to a grayscale
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

    # Find the chess board corners
    ret, corners = cv2.findChessboardCorners(gray, (9,6),None)
    print(corners)
    # if chessboard corners are detected
    if ret == True:
    
        # Draw and display the corners
        img = cv2.drawChessboardCorners(img, (9,6), corners,ret)
        cv2.imshow('Chessboard',img)
        cv2.waitKey(0)

    elif ret == False:
        cv2.imshow(window_name, img)
        cv2.setMouseCallback(window_name, click_event, param= {'img': img, 'name': f'Image{idx}'})
        cv2.waitKey(0)
        cv2.destroyAllWindows()



[[[619.1612  319.1798 ]]

 [[619.12994 354.84903]]

 [[619.0211  390.90298]]

 [[618.7946  426.566  ]]

 [[619.3388  463.98865]]

 [[618.8307  501.92792]]

 [[619.121   540.15546]]

 [[618.54236 578.6859 ]]

 [[619.7425  618.4025 ]]

 [[583.3251  318.7181 ]]

 [[583.18225 353.68164]]

 [[582.73846 390.14258]]

 [[582.93506 426.35675]]

 [[582.1687  463.8268 ]]

 [[582.2361  501.20258]]

 [[581.2969  540.43353]]

 [[581.3998  578.80646]]

 [[580.907   619.0484 ]]

 [[546.6431  317.12076]]

 [[545.92944 352.93387]]

 [[545.5869  389.02826]]

 [[544.99866 426.2418 ]]

 [[544.50494 463.43008]]

 [[543.61255 501.54608]]

 [[543.3274  540.1849 ]]

 [[542.3612  579.2098 ]]

 [[543.4806  619.10114]]

 [[509.5606  316.4879 ]]

 [[509.05997 351.9201 ]]

 [[507.96918 388.78214]]

 [[507.53644 425.38687]]

 [[506.19733 463.17084]]

 [[505.51132 501.31464]]

 [[504.8001  540.6175 ]]

 [[504.4324  579.2838 ]]

 [[501.42184 619.5486 ]]

 [[472.35645 315.01434]]

 [[471.09363 350.9698 ]]

 [[470.53583

UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: []


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

460 400
 Manual Points: [460, 400]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

633 408
 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

444 612
 Manual Points: [460, 400, 633, 408, 444, 612]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

652 616
 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

[[[684.3509  384.82077]]

 [[679.3264  408.22852]]

 [[672.57983 433.42215]]

 [[665.4786  455.7119 ]]

 [[657.7528  482.4011 ]]

 [[651.0713  508.5048 ]]

 [[641.5     537.     ]]

 [[634.9928  563.7544 ]]

 [[625.      593.5    ]]

 [[664.57745 386.3546 ]]

 [[657.      411.     ]]

 [[648.0049  434.42917]]

 [[641.33984 460.66608]]

 [[635.1723  481.63254]]

 [[627.25006 509.27853]]

 [[618.      536.     ]]

 [[610.      563.5    ]]

 [[601.5     591.5    ]]

 [[641.46844 388.93036]]

 [[635.      411.5    ]]

 [[628.30597 434.7713 ]]

 [[621.37744 457.90997]]

 [[612.      484.     ]]

 [[604.4865  508.68222]]

 [[596.      535.5    ]]

 [[587.5     562.5    ]]

 [[578.5     589.5    ]]

 [[621.5446  390.04144]]

 [[613.      412.5    ]]

 [[607.5481  435.3162 ]]

 [[599.225   458.641  ]]

 [[590.      484.5    ]]

 [[582.5     509.5    ]]

 [[575.3681  534.78436]]

 [[565.7694  560.93933]]

 [[556.06244 588.4744 ]]

 [[602.5493  392.4669 ]]

 [[594.7682  413.15585]]

 [[584.856  

UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

238 221
 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

518 234
 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

250 633
 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

577 604
 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

[[[615.11224 245.22137]]

 [[605.4579  277.57898]]

 [[597.72015 309.0452 ]]

 [[588.32745 342.0754 ]]

 [[577.21027 377.12292]]

 [[566.9543  412.5758 ]]

 [[555.33466 450.81696]]

 [[543.5104  490.0003 ]]

 [[531.39514 530.4253 ]]

 [[583.8716  247.96558]]

 [[573.5     279.     ]]

 [[564.79034 310.45016]]

 [[554.66815 343.76978]]

 [[543.6586  377.31082]]

 [[531.93744 412.22617]]

 [[521.31714 450.11264]]

 [[509.22757 488.62106]]

 [[494.47452 528.85205]]

 [[551.59515 252.0117 ]]

 [[544.1858  281.22388]]

 [[532.8377  312.74084]]

 [[521.354   344.86002]]

 [[509.6339  379.3023 ]]

 [[498.07413 414.69965]]

 [[487.9224  449.85275]]

 [[475.55273 487.1503 ]]

 [[461.58655 524.94305]]

 [[522.47894 254.40756]]

 [[512.8044  283.56244]]

 [[502.26978 314.49646]]

 [[489.2897  347.19513]]

 [[479.04297 379.48004]]

 [[466.5     413.5    ]]

 [[455.31787 448.58615]]

 [[441.5777  485.47186]]

 [[427.23453 523.67883]]

 [[492.9123  256.98264]]

 [[482.5     286.5    ]]

 [[470.87302

UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

478 300
 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

687 302
 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

458 606
 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

686 611
 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606, 686, 611]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606, 686, 611]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606, 686, 611]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606, 686, 611]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606, 686, 611]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606, 686, 611]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606, 686, 611]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606, 686, 611]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606, 686, 611]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606, 686, 611]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606, 686, 611]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606, 686, 611]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606, 686, 611]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606, 686, 611]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606, 686, 611]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606, 686, 611]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606, 686, 611]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606, 686, 611]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606, 686, 611]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606, 686, 611]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606, 686, 611]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606, 686, 611]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

 Manual Points: [460, 400, 633, 408, 444, 612, 652, 616, 238, 221, 518, 234, 250, 633, 577, 604, 478, 300, 687, 302, 458, 606, 686, 611]


UnboundLocalError: cannot access local variable 'coord_undetec' where it is not associated with a value

[[[532.33136 334.95193]]

 [[542.68945 364.4363 ]]

 [[552.8438  393.5891 ]]

 [[563.2148  423.66486]]

 [[573.49744 453.999  ]]

 [[584.31067 484.18005]]

 [[594.65765 514.5627 ]]

 [[605.46783 545.24164]]

 [[615.80646 576.095  ]]

 [[502.43515 345.01373]]

 [[512.55115 374.54477]]

 [[523.01044 404.54834]]

 [[533.11774 434.4352 ]]

 [[543.50134 464.53717]]

 [[553.5397  494.99368]]

 [[563.71606 525.459  ]]

 [[574.59406 556.21655]]

 [[585.40466 587.171  ]]

 [[472.35928 355.38593]]

 [[482.5584  384.8062 ]]

 [[492.58423 415.02182]]

 [[503.07162 444.9724 ]]

 [[513.0205  474.95178]]

 [[523.24646 505.8489 ]]

 [[533.86725 536.59204]]

 [[544.35406 567.26416]]

 [[554.8256  598.28455]]

 [[441.83258 365.4596 ]]

 [[451.96396 395.42828]]

 [[461.95624 425.5404 ]]

 [[472.41022 455.46805]]

 [[482.70306 486.0733 ]]

 [[492.8433  516.7761 ]]

 [[502.9153  547.4647 ]]

 [[513.63916 578.6487 ]]

 [[523.80865 609.9243 ]]

 [[411.18796 375.94733]]

 [[421.51627 406.4626 ]]

 [[431.6498 

In [ ]:
print('points', points)

In [ ]:

#gray_scaled_img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)

def click_event(event, x, y, flags, param):
    current_img = param['img']
    current_name = param['name']
    if event == cv2.EVENT_LBUTTONDBLCLK:
        print(x,y) # coordinate
        font = cv2.FONT_HERSHEY_SIMPLEX
        cv2.putText(current_img, f'{x}, {y}', (x,y), font, 1, (255,0,0), 2)
        cv2.imshow(window_name, current_img)
    
    if event == cv2.EVENT_RBUTTONDBLCLK:
        print(x,y)
        font = cv2.FONT_HERSHEY_SIMPLEX
        b,g,r = current_img[y,x] 
        cv2.putText(img,f'{b}, {g}, {r}', (x,y), font, 1, (255, 255,0), 2)
        cv2.imshow(window_name, current_img)

def resize(img, scale_percentage):
    width = int(img.shape[1]* scale_percentage/100)
    height = int(img.shape[0] * scale_percentage/100)
    dim = (width, height)

    resized_img = cv2.resize(img, dim, interpolation= cv2.INTER_AREA)
    return resized_img

window_name = 'chessboard_tool'
img1 = cv2.imread('img1.jpg')
img1 = cv2.drawChessboardCorners(img, (7,6), corners,ret)

#img1 = resize(img1, scale_percentage= 20)
cv2.imshow(window_name, img1)
cv2.setMouseCallback(window_name, click_event, param= {'img': img1, 'name': 'Image1'})
cv2.waitKey(0)
cv2.destroyAllWindows()



In [ ]:
window_name = 'chessboard_tool'
img2 = cv2.imread('img2.jpg',1)

img2 = resize(img2, scale_percentage= 40)
cv2.imshow(window_name, img2)
cv2.setMouseCallback(window_name, click_event,param= {'img': img2, 'name': 'Image2'})
cv2.waitKey(0)

cv2.destroyAllWindows()